import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { SiteHeader } from "@/components/layout/site-header";
import { SectionIndex } from "@/components/layout/section-index";
import { SiteFooter } from "@/components/layout/site-footer";
import "./globals.css";

// Helvetica Neue (pedida en docs/DESIGN_SYSTEM.md) es una fuente propietaria
// de Monotype: no está en Google Fonts y no se puede auto-hostear sin
// licencia. Inter es el reemplazo elegido: variable, muy usada en
// SaaS/landings modernas y con la neutralidad que pide AGENTS.md.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// El contenido de la página sigue siendo [PLACEHOLDER] (docs/DECISIONS.md),
// así que no se define título/descripción "definitivos" todavía
// (docs/SEO_GEO.md pide justamente evitarlo). El noindex es lo único que
// corresponde fijar ya: sección 15 de ese documento pide que el sitio no
// se indexe mientras exista contenido demostrativo.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SiteHeader />
        {/* Índice lateral: fijo, solo desde 1280px. Va fuera de <main>
            para que no lo alcance el `inert` que el menú móvil aplica al
            contenido principal. */}
        <SectionIndex />
        {/* flex-1: empuja el footer al fondo de la ventana aunque el
            contenido no llegue a llenarla. */}
        <main className="flex-1">{children}</main>
        {/* Fuera de <main> a propósito: <footer> es un landmark propio y
            no debe anidarse dentro del contenido principal. */}
        <SiteFooter />
      </body>
    </html>
  );
}
