import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { SiteHeader } from "@/components/layout/site-header";
import "./globals.css";

// Helvetica Neue (pedida en docs/DESIGN_SYSTEM.md) es una fuente propietaria
// de Monotype: no está en Google Fonts y no se puede auto-hostear sin
// licencia. Inter es el reemplazo elegido: variable, muy usada en
// SaaS/landings modernas y con la neutralidad que pide AGENTS.md.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SiteHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
